apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: pacman-cluster1                           
  namespace: pacman
  labels:
    name: pacman
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: application-portability/lab-7-assets/overlays/cluster1
spec:
  channel:  pacman/pacmanchannel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: pacmancluster1
