apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: web-app-channel
  namespace: web-app
spec:
  pathname: 'https://github.com/open-cluster-management/labs.git'
  type: GitHub
