apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: httpd                           
  namespace: simple-app
  labels:
    app: httpd
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: application-portability/lab-4-assets
spec:
  channel:  simple-app/federation
  placement: 
    placementRef: 
      kind: PlacementRule
      name: cluster1only     
