apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: gcp-apache-subscription
  namespace: apache-test
  labels:
    cloud: Google
  annotations:
    apps.open-cluster-management.io/github-path: kustomize-app/overlays/gcp
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: apache-test/apache-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: gcp-clusters
